#this file is used as global configuration file
defaults: &defaults
  authentication_method: ldap-stub #ldap, ldap-stub, openid
  #ldap means that wiki will be accessible only for users having ldap accound
  #ldap-stub is ussualy used in develeopment enviroment (usernam==pasword)
  #openid means that wiki will be accessible only for users having openid accound
  
  ldap:
    port: 389
    host: ldap.stuba.sk
    base_dn: ou=People,dc=stuba,dc=sk

  lock_timeout: 30

  extension_icons:
    default: page_white.png
    pdf: page_white_acrobat.png
    gif: page_white_picture.png
    jpg: page_white_picture.png
    jpeg: page_white_picture.png
    png: page_white_picture.png
    txt: page_white_text.png
    doc: page_white_word.png
    docx: page_white_word.png
    ppt: page_white_powerpoint.png
    pptx: page_white_powerpoint.png
    zip: page_white_zip.png
    xls: page_white_excel.png
    xlsx: page_white_excel.png
    rb: page_white_ruby.png
    c: page_white_c.png
    h: page_white_h.png
    php: page_white_php.png

  page_part:
    saving_time: 5


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
