#this file is used as global configuration file
defaults: &defaults
  authentication_method: ldap #ldap, openid
  #ldap means that wiki will be accessible only for users having ldap accound
  #openid means that wiki will be accessible only for users having openid accound
    
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
